### ISSUE TITLE
ProjectTo(): int <-> Color conversion leads into System.ArgumentException

### ISSUE THREAD

**Issue by ghost** [AutoMapper/AutoMapper.EF6#10]
Hi,

i want to save color into a database and read it back. Therefore i use an INT in the database. I implemented TypeConverters. While reading the entries from the database i got a System.ArgumentException.

Maybe i doing wrong. Please see attached project. Thank you.

[AutoMapperConsole.zip](https://github.com/AutoMapper/AutoMapper.EF6/files/905162/AutoMapperConsole.zip)

regards
Kai

**Comment by lbargaoanu** [comment]
But why do you need AM for that? By default EF will persist an enum as int.
https://msdn.microsoft.com/en-us/library/hh859576(v=vs.113).aspx

**Comment by ghost** [comment]
System.Color is not an enum: https://msdn.microsoft.com/en-us/library/system.drawing.color.aspx

regards
Kai

**Comment by lbargaoanu** [comment]
Aha :) ProjectTo works with ProjectUsing, Map with ConvertUsing.
