### ISSUE TITLE
Strongly signed

### ISSUE THREAD

**Issue by tsage080667** [AutoMapper/AutoMapper.EF6#12]
Hi,

I am having an issue registering the Nuget package into the GAC. I know it's not ideal, but that's how they are doing things here. I am getting an error indicating that the DLL is not strongly signed. Is this something that will change in the future?

Tim

**Comment by lbargaoanu** [comment]
See https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection/issues/13
