### ISSUE TITLE
Package version 1.0.0 on NuGet appears broken

### ISSUE THREAD

**Issue by apmorton** [AutoMapper/AutoMapper.EF6#14]
as per title - 0.6.0 works for me, 1.0.0 attempts to reference AutoMapper.dll 0.0.0, and fails.
Additionally, looks like the code here claims to be version 0.6.0 anyway - 1.0.0 is also 7 months old, vs 0.6.0 being 2 months old.

**Comment by jbogard** [comment]
Oh my, I seem to really have screwed something up.

**Comment by jbogard** [comment]
OK I released a 1.1 version that's the *right* version.

**Comment by apmorton** [comment]
looks like the 1.1 version has removed the extension methods that contain predicates - was this an intentional change, and if so, where is the source code reflecting this change?

for reference, I am referring to the functions that look like the following:
```c#
public static Task<TDestination> ProjectToSingleOrDefaultAsync<TSource, TDestination>(this IQueryable<TSource> queryable, Expression<Func<TSource, bool>> predicate, IConfigurationProvider config)
{
    return queryable.Where(predicate).ProjectTo<TDestination>(config).DecompileAsync().SingleOrDefaultAsync();
}
```

**Comment by jbogard** [comment]
Gah. Fixed that too.

Sigh.

**Comment by mycroes** [comment]
It seems that the DLL is still referencing `AutoMapper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005` (at least, that's what DotPeek tells me).

**Comment by jbogard** [comment]
I think your NuGet client may be broken?

**Comment by mycroes** [comment]
That's what Ithought when my colleague pointed me to the issue, so I
manually downloaded the package from the nuget website directly. The other
references (DelegateDecompiler, EF) in the package are actually OK.

Op do 29 mrt. 2018 18:18 schreef Jimmy Bogard <notifications@github.com>:
