### ISSUE TITLE
DLLs in NuGet packages appear not to be signed

### ISSUE THREAD

**Issue by SOHODeveloper** [AutoMapper/AutoMapper.EF6#17]
I just tried the last three versions of AutoMapper.EF6 in a project in which my assembilies were signed and the AutoMapper.EF6 dll would fail to load.  The message was something on the order of "a strongly named assembly is needed".  I looked at the dll with ILDASM and did not see the required key information.

**Comment by jbogard** [comment]
Use the StrongNamer package it will fix it.
