### ISSUE TITLE
Nuget version depends on incorrect Automapper dll 

### ISSUE THREAD

**Issue by ellims** [AutoMapper/AutoMapper.EF6#19]
I'm not sure if it's a proper place for such issue, but looks like it has bad reference on Automapper version 0.0.0.0
![image](https://user-images.githubusercontent.com/9704486/41892578-47a89b5e-7921-11e8-8a5b-1e940c826592.png)

**Comment by jbogard** [comment]
Looks like you’re on an older NuGet client.

**Comment by DBeath** [comment]
I'm also seeing this issue. Using NuGet Package Manager 4.6.0 in Visual Studio Enterprise 2017, and the same with the latest version of the NuGet CLI. Tried with both .NET 4.5.2 and 4.7.2. Same issue with a clean install of VS2017 on a colleague's computer.
![automapperef6issue](https://user-images.githubusercontent.com/2762706/48552606-6089f000-e8d9-11e8-914f-4bc7ca8edd13.PNG)

**Comment by lbargaoanu** [comment]
Yes, apparently the reference is broken. A PR is welcome.

**Comment by jbogard** [comment]
Updated to 8.0
