### ISSUE TITLE
EF7?

### ISSUE THREAD

**Issue by weitzhandler** [AutoMapper/AutoMapper.EF6#2]
Any plans to support EF7?

**Comment by jbogard** [comment]
Yep. I'll create a new repo for it though, similar to how EF6 and 7 are separate.

**Comment by weitzhandler** [comment]
Awesome! Looking forward.
Thanks!

**Comment by mkelley82** [comment]
So where are you at on ef7 support?

**Comment by jbogard** [comment]
Well, no repo yet :)

**Comment by rondefreitas** [comment]
@jbogard, I'm guessing hazzik/DelegateDecompiler#66 is what we're waiting on to get this going for EF7?
