### ISSUE TITLE
Can't use IValueConverter

### ISSUE THREAD

**Issue by amei130** [AutoMapper/AutoMapper.EF6#20]
public class CurrencyFormatter : IValueConverter<decimal, string> {
    public string Convert(decimal source)
        => source.ToString("c");
}

Mapper.Initialize(cfg => {
   cfg.CreateMap<Order, OrderDto>()
       .ForMember(d => d.Amount, opt => opt.ConvertUsing<CurrencyFormatter, decimal>());
   cfg.CreateMap<OrderLineItem, OrderLineItemDto>()
       .ForMember(d => d.Total, opt => opt.ConvertUsing<CurrencyFormatter, decimal>());
});

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
