### ISSUE TITLE
Support NETCOREAPP3.1 or NETSTANDARD2.1

### ISSUE THREAD

**Issue by tomasfabian** [AutoMapper/AutoMapper.EF6#23]
EF 6.4 was ported to NETSTANDARD/NETCORE, could you please support these target frameworks too?

Thank you, Tomas

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by tomasfabian** [comment]
Hi @lbargaoanu,
I added a pull request:
https://github.com/AutoMapper/AutoMapper.EF6/pull/24

Do you have any tests? I tried only `ProjectToFirst` and `ProjectToListAsync`

Regards Tomas

**Comment by lbargaoanu** [comment]
Feel free to add a test project. I don't see any tests either.
