### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by papiermache** [AutoMapper/AutoMapper.EF6#26]
hello I have nuget installed this pkg. I added "using Automapper" to class file (namespace ".EF6" doesn't exist). I write "Mapper.CreateMap...." and get error "Mapper does not contain a definition for CreateMap".
How to use this pkg?

**Comment by jbogard** [comment]
I haven't updated this project in a long time, you can copy the extension methods that you're interested in.

**Comment by papiermache** [comment]
Ok thx, I saw that last update on one file was 2 mths ago so I assumed the proj was still current; I’ll go with the Extensions.
Regards, Rick.
