### ISSUE TITLE
Nuget package targets outdated

### ISSUE THREAD

**Issue by panizza** [AutoMapper/AutoMapper.EF6#27]
Hi, the nuget package is outdated and targets .NETFramework 4.6.1 but not .NETStandard, can you please update the nuget package?

Thanks

**Comment by lbargaoanu** [comment]
@jbogard We should publish a new version. @panizza
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by Khaos66** [comment]
+1

**Comment by lbargaoanu** [comment]
Perhaps a CI build would help here. Then an up to date MyGet build would be available anytime. A PR is welcome. You can check the core project for inspiration.

**Comment by mudassir014** [comment]
Hey @jbogard, I would like to take up this issue.
Also, I tried to build nuget package for this project and I got the expected folders, Is this a CI issue?

**Comment by lbargaoanu** [comment]
See how CI is implemented in the other AM projects and do the same.
