### ISSUE TITLE
Add Ctor for GenerateEntityFrameworkPrimaryKeyPropertyMaps that takes in an instance of the DBContent

### ISSUE THREAD

**Issue by penfold** [AutoMapper/AutoMapper.EF6#28]
I'm using EF6.4, and I need to pass an instance into GenerateEntityFrameworkPrimaryKeyPropertyMaps() instead of it doing a new.

Is it possible to add another ctor? (I'm currently using a custom version of GenerateEntityFrameworkPrimaryKeyPropertyMaps to achieve this.)
```
public GenerateEntityFrameworkPrimaryKeyPropertyMaps(TDatabaseContext dbContext)
        {
            _context = dbContext;
        }
```

**Comment by lbargaoanu** [comment]
Wrong repo.
