### ISSUE TITLE
State of 2.1.0

### ISSUE THREAD

**Issue by mattletw** [AutoMapper/AutoMapper.EF6#30]
Hi!

Quick question, what would be the state of the current 2.1.0 version?
I am asking this because our software has a dependency on EF6.2. We would like to update to 6.4 so that we can make our applications to run on multiple platforms.

Currently this package is the last dependency that prevents us from doing this. As far we did notice, is that there is already a 2.1.0 version on your development nuget server. Is this package as well ready to be pushed towards the official nuget.org server?

Thanks in advance!

Kind Regards,
Mattletw

**Comment by lbargaoanu** [comment]
What's missing here is a release script similar to the base package. A PR is welcome.

**Comment by mattletw** [comment]
Thank you for your input.  So as far I understand, implementing/replacing the current githubactions pipeline with a similar setup as the Automapper repository itself would help.

I will take some time the upcoming week to implement this and a PR will follow.

**Comment by mattletw** [comment]
@lbargaoanu My apologies for not responding to this issue. I've just created a PR to implement a similar like CI/Release flow as in the base package.
