### ISSUE TITLE
Default value on "...OrDefault" operations

### ISSUE THREAD

**Issue by kallebysantos** [AutoMapper/AutoMapper.EF6#33]
Would be nice in "OrDefault" operations if had an overload that accepts an default object of the same TSource's type to project, like main Linq "OrDefault" operations where you can pass an default value.

Like this overload from Linq
`public static TSource FirstOrDefault<TSource>(this IQueryable<TSource> source, TSource defaultValue);`

**Comment by lbargaoanu** [comment]
A PR is welcome. Or maybe you can write your own extension method.
