### ISSUE TITLE
ProjectToSingle breaks if using Automapper 4.1.1

### ISSUE THREAD

**Issue by rajeev-shenoy** [AutoMapper/AutoMapper.EF6#5]
Possibly other extensions may be broken when using Automapper 4.1.1

**Comment by jslatts** [comment]
If you grab https://github.com/AutoMapper/AutoMapper.EF6/blob/master/src/AutoMapper.EF6/EntityFrameworkExtensions.cs and add it directly to your project, it works fine. I think it is just the Nuget package config that is broken, but I'm afraid I don't understand enough about Nuget (specifically testing dev packages) to generate a PR with a fix.

Anyway, it looks like it could be this line of the project.json:
https://github.com/AutoMapper/AutoMapper.EF6/blob/master/src/AutoMapper.EF6/project.json#L17

**Comment by rajeev-shenoy** [comment]
The problem with ProjectToSingle is caused by this line:
https://github.com/AutoMapper/AutoMapper.EF6/blob/master/src/AutoMapper.EF6/EntityFrameworkExtensions.cs#L60

The QueryableExtensions in Automapper 4.1.1 no longer contain a method ProjectTo with the following signature:

```
  queryable.ProjectTo<TDestination>().Decompile().Single();
```

Looking at the source for QueryableExtensions in Automapper 4.1.1, it looks like this will need to be changed to:

```
 queryable.ProjectTo<TDestination>(null, Mapper.Engine).Decompile().Single();
```

I have modified my code to use the above method from QueryableExtensions rather than the ProjectToSingle from the EntityFrameworkExtensions. 

However, you will need to fix the EntityFrameworkExtensions methods to work with Automapper 4.1.1 for it to be of any use.

**Comment by jbogard** [comment]
I pushed out a new version. That broke because of 4.0 using optional parameters. I don't use optional parameters anymore.

**Comment by rajeev-shenoy** [comment]
Ok, I will get the latest package.

Thanks.
