### ISSUE TITLE
When I try to translate enum to string,I get a exception

### ISSUE THREAD

**Issue by ArthurChang01** [AutoMapper/AutoMapper.EF6#6]
Hi:
This tool is really powerful, but I get some problem,can you help me?

My POCO has some properties uses enum type,and when I try to map this POCO to my DTO(Data transfer object) which mapping properties uses string type, my program throw a exception; it said: EF can not translate some method(sorry I forget the method name...)

by the way, I put Enum.GetName method into Automapper config.... maybe it is root cause, but what if I really want this feature, what is best practice?

**Comment by mjamro** [comment]
Please paste your DTO/Entity classes and mapper configuration.

**Comment by lbargaoanu** [comment]
This should work by default.
