### ISSUE TITLE
Pass MapperConfigurationExpression?

### ISSUE THREAD

**Issue by fjdiazt** [AutoMapper/AutoMapper.EF6#9]
I usually use Automapper with a custom MapperConfigurationExpression to, among other things, set CreateMissingTypeMaps = true (yes, I am aware of the consequences).

Is there a way to pass the configuration to the extension? How will this work with a non-static mapper?

**Comment by jbogard** [comment]
This project doesn't really have anything to do with configuration setup stuff. With the static version you don't pass anything in, with an instance-based version of configuration, you need to pass in your configuration object. That's it.

**Comment by fjdiazt** [comment]
I see. I assume there is not recommended way to let the extension resolve the IConfigurationProvider by itself to avoid passing it on every call to project, is there?

**Comment by jbogard** [comment]
Besides using the static registration of Mapper.Initialize? That's what I'd do, just use that. Otherwise I don't know how the extension would figure out how to resolve the configuration instance. The static API is a convenient way to have a "well-known" location for mapper configuration.

**Comment by fjdiazt** [comment]
Understood, thank you. I made it work with the static registration.
